sudo: false
language: python
install: pip install tox
script: tox
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.7
      dist: xenial
      env: TOXENV=lint
