from typing import Any, Callable, Iterable, MutableSequence, Optional, Tuple, TypeVar, Generic, Iterator


def recursive_repr(fillvalue: str = ...): ...
T = TypeVar('T', covariant=True)

class SortedList(MutableSequence[T]):
    DEFAULT_LOAD_FACTOR: int = ...
    def __init__(self, iterable: Iterable[T]=..., key: None=...) -> None: ...
    def __new__(cls: Any, iterable: Iterable[T]=..., key: Callable[[T], Any]=...) -> SortedList[T]: ...
    @property
    def key(self) -> Optional[Callable[[T], Any]]: ...
    def clear(self) -> None: ...
    def add(self, value) -> None: ...
    def update(self, iterable: Iterable[T]) -> Any: ...
    def __contains__(self, value) -> bool: ...
    def discard(self, value) -> None: ...
    def remove(self, value) -> None: ...
    def __delitem__(self, index: Any): ...
    def __getitem__(self, index: Any): ...
    def __setitem__(self, index: Any, value: Any) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def reverse(self) -> None: ...
    def islice(self, start: int=..., stop: int=..., reverse: bool=...) -> Iterable[T]: ...
    def irange(self, minimum=..., maximum=..., inclusive: Tuple[bool, bool]=..., reverse: bool=...) -> Any: ...
    def __len__(self) -> int: ...
    def bisect_left(self, value) -> int: ...
    def bisect_right(self, value) -> int: ...
    bisect: Any = ...
    def count(self, value) -> int: ...
    def copy(self) -> SortedList[T]: ...
    __copy__: Any = ...
    def append(self, value: Any) -> None: ...
    def extend(self, values: Any) -> None: ...
    def insert(self, index: Any, value: Any) -> None: ...
    def pop(self, index: int=...) -> T: ...
    def index(self, value: Any, start: int=..., stop: int=...) -> int: ...
    def __add__(self, other: SortedList[T]) -> SortedList[T]: ...
    __radd__: Any = ...
    def __iadd__(self, other: Iterable[T])-> SortedList[T]: ...
    def __mul__(self, num: int) -> SortedList[T]: ...
    __rmul__: Any = ...
    def __imul__(self, num: int) -> SortedList[T]: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    def __reduce__(self): ...

def identity(value: Any) -> T: ...

class SortedKeyList(SortedList[T]):
    def __init__(self, iterable: Iterable[T]=..., key: Callable[[T], Any]=...) -> None: ...
    def __new__(cls: Any, iterable: Iterable[T]=..., key: Callable[[T], Any]=...) -> Any: ...
    @property
    def key(self) -> Callable[[T], Any]: ...
    def clear(self) -> None: ...
    def add(self, value) -> None: ...
    def update(self, iterable: Iterable[T]) -> None: ...
    def __contains__(self, value) -> bool: ...
    def discard(self, value) -> None: ...
    def remove(self, value) -> None: ...
    def irange(self, minimum=..., maximum=..., inclusive: Tuple[bool, bool]=..., reverse: bool=...) -> Any: ...
    def irange_key(self, min_key: Optional[Any] = ..., max_key: Optional[Any] = ..., inclusive: Any = ..., reverse: bool = ...): ...
    def bisect_left(self, value) -> int: ...
    def bisect_right(self, value) -> int: ...
    bisect: Any = ...
    def bisect_key_left(self, key: Any) -> int: ...
    def bisect_key_right(self, key: Any) -> int: ...
    bisect_key: Any = ...
    def count(self, value) -> int: ...
    def copy(self): ...
    __copy__: Any = ...
    def index(self, value, start: int=..., stop: int=...) -> Any: ...
    def __add__(self, other: Iterable[T]) -> Any: ...
    __radd__: Any = ...
    def __mul__(self, num: int) -> SortedKeyList[T]: ...
    def __reduce__(self): ...
SortedListWithKey = SortedKeyList
